"""Column types for the 13 raw tables, transcribed from docs/data_dictionary.pdf.

VARCHAR(n) and TEXT map to VARCHAR; the other types are kept as DuckDB types.
Column order matches the raw CSV headers.
"""

V = "VARCHAR"
TS = "TIMESTAMP"
DATE = "DATE"
BOOL = "BOOLEAN"
INT = "INTEGER"
MONEY = "DECIMAL(15,2)"
COORD = "DECIMAL(10,7)"

TABLE_SCHEMAS: dict[str, dict[str, str]] = {
    # --- Dimension tables ---------------------------------------------------
    "customers": {
        "customer_id": V,
        "document_number": V,
        "document_type": V,
        "first_name": V,
        "last_name": V,
        "date_of_birth": DATE,
        "gender": V,
        "email": V,
        "mobile_phone": V,
        "landline_phone": V,
        "address": V,
        "city": V,
        "state": V,
        "country": V,
        "postal_code": V,
        "detected_accent": V,
        "segment": V,
        "credit_score": INT,
        "estimated_monthly_income": "DECIMAL(12,2)",
        "occupation": V,
        "marital_status": V,
        "education_level": V,
        "registration_date": TS,
        "registration_branch_id": V,
        "customer_status": V,
        "last_updated": TS,
        "accepts_marketing": BOOL,
    },
    "products": {
        "product_id": V,
        "customer_id": V,
        "product_type": V,
        "product_number": V,
        "currency": V,
        "current_balance": MONEY,
        "credit_limit": MONEY,
        "interest_rate": "DECIMAL(5,2)",
        "opening_date": DATE,
        "expiration_date": DATE,
        "opening_branch_id": V,
        "product_status": V,
        "opening_channel": V,
        "has_linked_app": BOOL,
        "days_past_due": INT,
        "last_transaction_date": TS,
        "last_updated": TS,
    },
    "branches": {
        "branch_id": V,
        "branch_code": V,
        "branch_name": V,
        "branch_type": V,
        "address": V,
        "city": V,
        "state": V,
        "country": V,
        "postal_code": V,
        "geographic_zone": V,
        "phone": V,
        "email": V,
        "opening_time": "TIME",
        "closing_time": "TIME",
        "has_atms": BOOL,
        "atm_count": INT,
        "has_teller_windows": BOOL,
        "teller_window_count": INT,
        "latitude": COORD,
        "longitude": COORD,
        "branch_opening_date": DATE,
        "branch_status": V,
    },
    "service_agents": {
        "agent_id": V,
        "employee_code": V,
        "first_name": V,
        "last_name": V,
        "email": V,
        "phone": V,
        "native_accent": V,
        "country_of_origin": V,
        "assigned_branch_id": V,
        "agent_type": V,
        "experience_level": V,
        "languages": V,
        "specialty": V,
        "hire_date": DATE,
        "avg_csat": "DECIMAL(3,2)",
        "total_monthly_interactions": INT,
        "agent_status": V,
        "work_shift": V,
    },
    "marketing_campaigns": {
        "campaign_id": V,
        "campaign_name": V,
        "description": V,
        "campaign_type": V,
        "campaign_objective": V,
        "promoted_product": V,
        "target_segment": V,
        "target_country": V,
        "start_date": DATE,
        "end_date": DATE,
        "budget": "DECIMAL(12,2)",
        "campaign_status": V,
        "expected_conversion_rate": "DECIMAL(5,2)",
    },
    # --- Reference tables ---------------------------------------------------
    "daily_exchange_rates": {
        "date": DATE,
        "source_currency": V,
        "target_currency": V,
        "exchange_rate": "DECIMAL(12,6)",
        "buy_rate": "DECIMAL(12,6)",
        "sell_rate": "DECIMAL(12,6)",
        "source": V,
    },
    # --- Fact tables --------------------------------------------------------
    "transactions": {
        "transaction_id": V,
        "transaction_date": TS,
        "process_date": DATE,
        "product_id": V,
        "customer_id": V,
        "transaction_type": V,
        "transaction_category": V,
        "amount": MONEY,
        "currency": V,
        "amount_usd": MONEY,
        "channel": V,
        "branch_id": V,
        "merchant_name": V,
        "merchant_category": V,
        "transaction_country": V,
        "transaction_city": V,
        "transaction_status": V,
        "response_code": V,
        "is_fraud": BOOL,
        "fraud_score": "DECIMAL(5,2)",
        "latitude": COORD,
        "longitude": COORD,
    },
    "call_center_interactions": {
        "interaction_id": V,
        "interaction_date": TS,
        "process_date": DATE,
        "customer_id": V,
        "agent_id": V,
        "interaction_type": V,
        "channel": V,
        "contact_reason": V,
        "reason_category": V,
        "duration_seconds": INT,
        "wait_time_seconds": INT,
        "was_resolved": BOOL,
        "requires_followup": BOOL,
        "detected_sentiment": V,
        "sentiment_score": "DECIMAL(3,2)",
        "customer_detected_accent": V,
        "agent_used_accent": V,
        "was_escalated": BOOL,
        "mentioned_products": V,
        "has_transcript": BOOL,
        "has_recording": BOOL,
    },
    "call_transcripts": {
        "transcript_id": V,
        "interaction_id": V,
        "process_date": DATE,
        "customer_id": V,
        "agent_id": V,
        "full_text": V,
        "customer_text": V,
        "agent_text": V,
        "detected_language": V,
        "detected_accent": V,
        "accent_confidence": "DECIMAL(3,2)",
        "detected_keywords": V,
        "mentioned_entities": V,
        "detected_intents": V,
        "main_topics": V,
        "transcription_model": V,
        "audio_quality": V,
        "duration_seconds": INT,
    },
    "satisfaction_surveys": {
        "survey_id": V,
        "survey_date": TS,
        "process_date": DATE,
        "interaction_id": V,
        "customer_id": V,
        "agent_id": V,
        "survey_type": V,
        "send_channel": V,
        "main_score": INT,
        "nps_category": V,
        "question_1_text": V,
        "question_1_response": INT,
        "question_2_text": V,
        "question_2_response": INT,
        "question_3_text": V,
        "question_3_response": INT,
        "open_comments": V,
        "comment_sentiment": V,
        "response_time_hours": "DECIMAL(8,2)",
        "campaign_response_rate": "DECIMAL(5,2)",
    },
    "digital_events": {
        "event_id": V,
        "event_date": TS,
        "process_date": DATE,
        "customer_id": V,
        "session_id": V,
        "event_type": V,
        "event_category": V,
        "channel": V,
        "platform": V,
        "browser": V,
        "app_version": V,
        "page_url": V,
        "page_title": V,
        "action": V,
        "element_id": V,
        "product_id": V,
        "event_value": MONEY,
        "duration_seconds": INT,
        "ip_address": V,
        "ip_country": V,
        "ip_city": V,
        "is_mobile": BOOL,
        "referrer": V,
        "utm_source": V,
        "utm_medium": V,
        "utm_campaign": V,
    },
    "complaints": {
        "complaint_id": V,
        "creation_date": TS,
        "process_date": DATE,
        "customer_id": V,
        "case_type": V,
        "category": V,
        "subcategory": V,
        "reception_channel": V,
        "affected_product_id": V,
        "related_branch_id": V,
        "origin_interaction_id": V,
        "description": V,
        "claimed_amount": MONEY,
        "currency": V,
        "priority": V,
        "status": V,
        "assigned_agent_id": V,
        "assignment_date": TS,
        "first_response_date": TS,
        "resolution_date": TS,
        "closing_date": TS,
        "sla_breached": BOOL,
        "resolution_days": INT,
        "resolution": V,
        "compensation_granted": MONEY,
        "resolution_satisfaction": INT,
        "is_repeat_complainer": BOOL,
    },
    "campaign_sends": {
        "send_id": V,
        "send_date": TS,
        "process_date": DATE,
        "campaign_id": V,
        "customer_id": V,
        "send_channel": V,
        "template_used": V,
        "subject": V,
        "send_status": V,
        "was_delivered": BOOL,
        "was_opened": BOOL,
        "open_date": TS,
        "was_clicked": BOOL,
        "click_date": TS,
        "click_count": INT,
        "had_conversion": BOOL,
        "conversion_date": TS,
        "conversion_value": MONEY,
        "open_device": V,
        "open_country": V,
        "failure_reason": V,
        "send_cost": "DECIMAL(10,4)",
    },
}
